### ISSUE TITLE
Wrong Swift syntax

### ISSUE THREAD

**Issue by leo-unglaub** [lucaslouca/parallax-table-view-header#2]
Hey,
in File `ParallaxTableHeaderView.swift#L22` you have an syntax error. You use the Objective-C style of adding options together. In swift you should use the pipe for that:

``` swift
self.subView.autoresizingMask = [.FlexibleLeftMargin, .FlexibleRightMargin, .FlexibleTopMargin, .FlexibleBottomMargin, .FlexibleHeight, .FlexibleWidth]
```

should be

``` swift
self.subView.autoresizingMask = .FlexibleLeftMargin | .FlexibleRightMargin | .FlexibleTopMargin | .FlexibleBottomMargin | .FlexibleHeight | .FlexibleWidth
```

Greetings
Leo

**Comment by lucaslouca** [comment]
Hello,

thanks for the info! 

Im using Xcode 7.0 beta, the syntax has changed for Swift 2.0. 

See also: http://www.rockhoppertech.com/blog/swift-2-optionsettype/
